sudo: required
dist: trusty
group: deprecated-2017Q3
os: linux
language: generic
services:
- docker
cache:
  apt: true
  ccache: true
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - secure: J0T+zrRBBzBnxoioCD378cRSJUF8Vms32QMmrENVVfuJl03oBQv0QxSatLEiD4PtRPrN00mJ8/k/HdqFQ0SN1yg6a00duOZ6C9jk6t/fExBO1LNhp3Z7lcaMUrNEyRN6sgfVeznDVTGj9jBQU2HNlwHk0UD9BNp/k+Bjhrtw7Njp9JTLZKBgxrXk0WZmfk0d75Q+9DajA1j2tSfWVpwzv6HMGfqIH1wsVEakBY+tnaE6EO3IdzdWHhf/iV+Tx0tL0Qz/6mejgSuoGLTJLmeTrceTTmsDlN3B95y+XfcYDs6EP7gpzN8Ffg/mLV8xJ2Myj7+b1o+smMJZE5tLuPIeAu0YsfkPNa/tNLotOlDxF72per0kXyNYbRf+JrpxiOu9pLCtdtd40V2SsiNhpQqHVy+b+wkkqo2syTHT+9UNkqEi3WFm6TqFuOeQNtDm6R0hRl/Talw/ZEeKs68z1Cf6VyBrZG5LqtOurtWlKwXCe/Tr1i2g4BEAcbywphtCCcfgMK9YSGQnjKkGk6k9gVEa2bneYLZz1RSh2OpXnIsIJOX7X0hNd5xtQDLgbpSUlKwVcEriWeGe12GCszKNX9gdEo2bHeq4xAJ6BE+ot745z9dc+nC2BJ6Su+I5L6zBg4m2FWn0TWhPvz/6JR26t6ls/E7m+hkwJTCHnIUiFmmzpEw=
  - secure: RLzlMhfLqwSBrZqJOVOd61suXBn+HtUR3vOZfuFYF/Qmjjj5TE41+rObZmzc54hP/ZL+OH6blnibpvfDXlX+eN38ivFQfuxkJIGL68SJsEwNBRwW39Yw6Hl5RdI41MLCH7ByN15wifLp1JKBilHJ7XGMOUjI7P0yl7JjX8GBXUCtJbVLRugo80/yn+XQ1NdnlpbpYHNjMEQFWSODPa3pSK5McWvyQjDZDgS+IkdrZmIYJPMa7bmKH5I/edUPSmXQT905FgEwq9u8XR0SyBopli21EK9l6GkXIIvmDTYz5vT26Apvi2B4Aoazlklg+KNRUJuLGerpt6kbnU0gMSUChVkFfFhOk6GRSN3a/AUfD2FOudvMhet2QvlPHx+GYdEUr5XVo5HW42pHsqfD6eDtHd8VLTsHP0q4C8V85fNMv21lkkehy2ry8fx/RRy6x4O2wg2mua+79UkGKXp75gMKzWEcth34PCFCOu37l2F8R/ANnrQ52K/8vIQ88TtU2OpYX89fHjLojBxu+WKEBGZH2LRPsZBOUHeeO5C/xKDrhZU24ORnMW8wg66Qg5GIX1KI4a8yp73Mpues5hzpJ6wkMuRrQt40ymKndLCjv8KSd+5BfP6Or/KIrzDNYdZaasjk7JNi6rcZmm9d3fTAo+Ja/mjpUCIOo3SX14luzVCJIig=
  - MAKEJOBS=-j5
  - RUN_TESTS=false
  - CHECK_DOC=0
  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
  - CCACHE_SIZE=400M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - PYTHON_DEBUG=1
  - WINEDEBUG=fixme-all
  - DOCKER_BUILD=false
  - secure: S+bfRgmz2STUPkuJ03qKstbPto2Hv2Wap5V5X0tbjfxbP8N2HawbllIK6n6LDwIZtPQk+VGGxuQoXuXAhu6aXJrjSIWEg/1wIo3/7f9KuAZGnkhSyX1urm6zMsjspcbCRkWaoRRHENhWBrag8lT76/Z0G3sA1a8bHrsPZ7ZWxFFgbn2bYzAlpn0VoFlDiZ3hqCu5I/UByTtqyVgX7seIQdWQ8djoUWRRdEnHmVsjf0HcXQMBjQay0c+wdYVucRTXa8s2tt7Je1COJMFaf790lhd74t1bZrPNaXb8+6H9N6nfIQ/19WaeXdWkdqPeYkwEeLfhPv3PjaAP+n1SshzhpwvEQ8vQF+Di38+88y9NKbpxI601pS+V4mtUE1BpRcXpvvZKVQ58SGMm43U1JsPuigZPwX0Cw6QwnYW32TVLsfzLjVChfOiljaTaRQ6GAzpnKXXoukpiKcMAwi4n9m5B7+bokvfRxDLwQ9DZu/NyWYH0S5cr9jUFYBk1acHLxrpa3yO8+XT6SRHd3m5E/w3nvH+i6YlgqR7RyN4QLepTrvmczintjRhooPCwe8voc8UJeh7HzCDvpCBIg937g6FX69Dv83klsPlpQsLL5D9v9c2sB+2zkB9TLHwLxJjcV9xL+v+mRiXgSSSOTXMY+a9gA4J5mEIV2nCU4S6iVdUWxd8=
  - secure: OSslmlPvJh9d/tEUtN0ijmGb747HTjD4O8tIFc3Z++YKVskcg8dyyugajZxaTyJbW0+uwWtoAH4+E79J2h49Hzi9mYdpIpBRvqe+WTx9n6n3Oq7ZnHKrQJCFnD2cd/Hlge1hTRxYO0fPI4enwtKDbt/id5K0O+ID9y43JI5bu+JZhy1ZpEUf1Hgwfe6pxTW5TOyMgFVHS1/OQHTzsAVbM1kixsHNI3AWSnnONrKlTsPCTIqnSn6EXqVPKsChPwhKfmD0vlylX2crr3JVQTRzaNMX7kEvy2uY10HmsCntZFIakb/lqc0ycatYJJuhbKRH22H0/xyLjwQCPcurIQPmB8O4IWeKve1KuZvu7waksmuynykcuaqNQpXQlAeKGQohAR89Xfs+YFnMdq7NHzUZ2LKdYUl5Qbp7+EfCFvWradQj/zu59efbnymUdjEjVOZbf2eoQUSbIDASMTgI8O6spW0OHCdx2RFF+7Sktw8B+kECF30kFCUXOkH2poYkV8SdKPPpAQNy2RyyEP7quqTSgS+oskxnOErTrnUOdtv69TpEfznKP5K238NUom+Vp2OJYJZ+Otz+sNlc0P0RA++1aMq2paekeg57L6tSJD1WpR03nxTOGuCjlW524A9UqfGihUeUJnovUjQNHL6zWVQe3PSXL7tfXVB6ORljB7X4Il0=
  matrix:
  - HOST=arm-linux-gnueabihf PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-arm-linux-gnueabihf"
    DEP_OPTS="NO_QT=1" CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat
    --enable-reduce-exports"
  - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PPA="ppa:bitcoin/bitcoin"
    PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.7 bc" RUN_TESTS=true GOAL="install"
    BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" MAKEJOBS="-j4"
  - HOST=i686-pc-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq"
    DEP_OPTS="NO_QT=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq
    --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
    USE_SHELL="/bin/dash" PYZMQ=true
  - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="NO_QT=1" PPA="ppa:bitcoin/bitcoin"
    PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.7 bc" RUN_TESTS=true GOAL="install"
    BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" MAKEJOBS="-j4"
  - HOST=x86_64-unknown-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="bc python3-zmq"
    DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq
    --enable-glibc-back-compat --enable-reduce-exports" CPPFLAGS="-DDEBUG_LOCKORDER
    -DENABLE_DASH_DEBUG" PYZMQ=true
  - HOST=x86_64-unknown-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="python3" DEP_OPTS="NO_WALLET=1"
    RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
  - HOST=x86_64-apple-darwin11 PPA="ppa:bitcoin/bitcoin" PACKAGES="cmake imagemagick
    libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev" BITCOIN_CONFIG="--enable-gui
    --enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"
  - HOST=x86_64-unknown-linux-gnu PPA="ppa:bitcoin/bitcoin" PACKAGES="bc python3-zmq"
    DEP_OPTS="NO_QT=1 NO_UPNP=1" GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat
    --enable-reduce-exports" PYZMQ=true DOCKER_BUILD=true
before_install:
- git clone https://github.com/dashpay/dash_hash
- travis_retry sudo apt-get install python3-pip python3-dev
- travis_retry sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
install:
- if [ "$PYZMQ" = "true" ]; then pip3 install pyzmq --user ; fi
- if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
  fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
- cd dash_hash && python3 setup.py install --user && cd ..
before_script:
- unset CC; unset CXX
- unset DISPLAY
- python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL);
  fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
- make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
- export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST
  --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
- mkdir build && cd build
- "../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (
  cat config.log && false)"
- make distdir VERSION=$HOST
- cd dashcore-$HOST
- "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG ||
  ( cat config.log && false)"
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
  V=1 ; false )
- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
- if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1;
  fi
- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
- cd ../..
- if [ "$DOCKER_BUILD" = "true" ]; then BUILD_DIR=build/dashcore-$HOST ./docker/build-docker.sh;
  fi
after_script:
- echo $TRAVIS_COMMIT_RANGE
- echo $TRAVIS_COMMIT_LOG
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$DOCKER_BUILD"
  = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./docker/push-docker.sh;
  fi
deploy:
  provider: releases
  api_key:
    secure: NpJB3GrArh4SmL4Wruj7mrVWrsVdKK6SwsPTXgahpKWivIbtb86yojqRFxWKbTfAj7ACxsS5XEbuyOs7y04lbFwnnR3GenWgvRpXiQNH+k+FYgFbZsQSAhqveUQeDH08etpR4RdC7NbULttGKz+n0dutUI1bADXatm4FSbdaztiohA9pfWwmTmzFHCUheklOHxKMTsKEVyAVpYmWaN6nfMa7lI7VJVQDNd6/heWVhTu45Ys8GkZMt2E11tZHaVpYwv1IhIiOkU+fg0ZhHT5c8GiHgObamPeW0gfU1OUTn7ORTNDVHdovbhtHbz9CRwMfvin0plM17FqQ6F+m60iziYSAKdwsv+GpCGZOy3AVoBX+66N2tSgjbrtDvSAPYFeMSIN1gbl769dupwWesjFWHF5265iTk+KSA8+VafdGpqblHUxG4qiKL4Da0ewwrpNfjrLWCq/sIeIPVGPavhHOjTiCBmdGh5fPW5VCZH0YhgwScMbm6H2S8I/pjmeD1LS2v3etFdRU+ddHIEqx/QeyjFza3QvC4RrFlHuu3uKfU0rCjgp6TOZ9Q9F3a59fDb5vcjLWFzf5bFajShownv6sPInll6pBRMYInjKPx9eztVKTSr7GcTifn79O7P1kZwzPbc9IXOrae8adhIgTO6CbWK9FT+ZZBBMRXwRBSrsRmbE=
  file: ".travis.yml"
  file: "dash-cli.exe"
  file: "dash-qt"
  file: "dash-cli"
  file: "dashd"
  file: "dash-tx"
  file: "dash-qt.exe"
  file: "dash-tx.exe"
  file: "dashd.exe"
  skip_cleanup: true
  on:
    repo: siliconlumen/dash
